name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Build and publish
        run: |
          cd Quizzler-Backend
          dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true -o out

      - name: Push to private repository
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/QuizzlerOrg/built-api
          cp out/quizzler-backend built-api/
          cd built-api
          git add quizzler-backend
          git commit -m "Update executable"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
